### ISSUE TITLE
viewing mapping rules taking far too long

### ISSUE THREAD

**Issue by calmacx** [CO-CONNECT/mapping-pipeline#138]
![image](https://user-images.githubusercontent.com/69473770/120788985-e833ba80-c528-11eb-9aa5-90a3756248ab.png)

Takes ~1 minute!

![image](https://user-images.githubusercontent.com/69473770/120789022-eff35f00-c528-11eb-8032-7ee0c709be75.png)

**Comment by spco** [comment]
I believe this has now been fixed.
