### ISSUE TITLE
Bad Response Time

### ISSUE THREAD

**Issue by calmacx** [CO-CONNECT/mapping-pipeline#384]
The dev-db test site is taking far to long to response, you can see there's a huge number of slow API requests being made by react:

![image](https://user-images.githubusercontent.com/69473770/153255889-e38cb903-2135-45c3-ab52-adedd70c9785.png)

taking something like 45 seconds to load the ScanReports page

test-db seems much quicker (there are also less scan reports)

**Comment by spco** [comment]
Fixed by #383
