### ISSUE TITLE
Scan Report not uploading on test-db

### ISSUE THREAD

**Issue by calmacx** [CO-CONNECT/mapping-pipeline#385]
Report uploads ok with no errors
![image](https://user-images.githubusercontent.com/69473770/153257356-2638a083-bae9-4387-a52c-12546cebf6aa.png)

followed by empty tables:
![image](https://user-images.githubusercontent.com/69473770/153257431-125f630f-09f8-4c8a-b8e3-7c0580b56bce.png)

scan report looks ok:
![image](https://user-images.githubusercontent.com/69473770/153257546-e1d77927-b66d-4483-aff2-bc1a9ae9b705.png)

**Comment by spco** [comment]
Could you please clarify - `model-test-db` or `ccnet-test-db`?

**Comment by calmacx** [comment]
Hmm this'll be ccnet ( https://ccom-dev.azurewebsites.net/)

Cheers for replying while away @spco , these "issues" were notes for me to not to forget in the stand-up. Will let you know if we don't figure it out

**Comment by calmacx** [comment]
More observations this morning

1. Can't upload on dev because the new changes arent letting me upload a new dataset (have to select an existing one)

2. Also fails to upload on prod

3. Now "uploading" on test with the Flag and Classification columns added
![image](https://user-images.githubusercontent.com/69473770/153369677-2720849a-d1ca-4e23-9eae-527f364adfdc.png)
No error was given when werent present and it says the upload was complete

4. Upload fails now with no error given 
![image](https://user-images.githubusercontent.com/69473770/153370019-1aa8860d-43b3-4fff-b01f-d17a69fe1bfe.png)
 
 Tables are present:
![image](https://user-images.githubusercontent.com/69473770/153370070-63ec53eb-f5d0-4c57-beff-3b0fb8d3b7e7.png)

First table is ok:
![image](https://user-images.githubusercontent.com/69473770/153370137-c8f62e4b-d57e-4787-ae95-8576a8825bc6.png)

All others are empty:
![image](https://user-images.githubusercontent.com/69473770/153370184-12179ad0-edab-4b74-aa28-0f095eebbadd.png)

Possible reason: empty cells?
![image](https://user-images.githubusercontent.com/69473770/153370306-f152c6b8-04dc-495e-a9d3-85705d5fa8b1.png)
